README、package.jsonの更新とuroborosql-fmt-napi.tgzの更新
future-architect/vscode-uroborosql-fmt pull request #2
Opened 2023-09-19 09:53 UTC by ppputtyo

### READMEの更新
uroborosql-fmtのREADMEを持ってきて、VSCode拡張機能仕様に一部変更しました。
具体的な変更点は以下のとおりです。
* デモを拡張機能仕様に変更
* wasmのデモに関する文章と画像を削除
* URLを絶対パスに変更
* インストール方法を拡張機能仕様に変更

### pakcage.jsonの更新
* authorを`Future Corporation`に変更
* publisherを`Future`に変更
* ライセンス情報、説明、キーワードなどを整備

### uroborosql-fmt-napi.tgzの更新
* `uroborosql-fmt-napi.tgz`を手動(CIを使わず)で作成して再パッケージ化
  * [成果物](https://github.com/future-architect/uroborosql-fmt/actions/runs/6196074488)

2023-09-19 10:27 UTC, ota-meshi requested changes
いくつかコメントを残しました。
これらに追加して
server/uroborosql-fmt-napi-0.0.0.tgzファイルは必要ですか？ご確認お願いします。

2023-09-19 10:27 UTC, ota-meshi commented on docs/Environment.md
> +# uroborosql-fmt
このドキュメントは必要ないと思います。

2023-09-19 10:27 UTC, ota-meshi commented on docs/options/complement_alias.md
> +# complement_alias
これらのオプションのドキュメントはuroborosql-fmtにリンクするだけではありませんか？このリポジトリに必要ですか？
また、そのほかのドキュメントも必要ない可能性があると思っています。確認していただけますか？

2023-09-22 09:05 UTC, abcd-ts commented
> server/uroborosql-fmt-napi-0.0.0.tgzファイルは必要ですか？
uroborosql-fmtのGitHub Actionsで生成したファイルをどこかに置いて、こちらのpublish用GitHub Actionsでそれをダウンロードするようにはできませんか？

現在私が .tgz をGithub actions上で作成するように修正しています。
このPRでは拡張機能用にpackage.json と readme.md のみを修正しているのだと思います。

2023-09-22 09:41 UTC, abcd-ts commented on docs/options/complement_alias.md
> +# complement_alias
川渕さんが勤務外なので、私の方で対応しました。

uroborosql-fmtのドキュメントを削除し、最低限の説明とオプションの説明を記述したREADMEに変更しています。
ご確認よろしくお願いします。

問題がなければ、こちらのブランチにpushし直そうと思います。

https://github.com/future-architect/vscode-uroborosql-fmt/blob/1-saito-fix-README/README.md

2023-09-22 10:02 UTC, ota-meshi approved these changes
LGTM!

2023-09-22 10:02 UTC, merged