Fix format even if workspace folder cannot be obtained
future-architect/vscode-uroborosql-fmt pull request #36
Opened 2023-10-30 07:13 UTC by tanzaku

workspace folderが取得できない場合でも、デフォルト設定でフォーマットするよう変更しました。
workspace folderが取得できた場合の挙動は変更前後で変わらないようにしています。

また、スネークケースの変数があったのでついでに直しています。

2023-10-30 14:55 UTC, ota-meshi requested changes

2023-10-30 14:55 UTC, ota-meshi commented on server/src/server.ts
> +  if (version !== textDocument.version) {
バージョンのチェックは`await determineConfigPath(uri, textDocument)`よりも後である必要があると思います。非同期中にバージョンが変更される可能性があるためです。

2023-10-31 00:43 UTC, tanzaku commented on server/src/server.ts
> +  if (version !== textDocument.version) {
ありがとうございます、見落としてました。
バージョンのチェックをdetermineConfigPathの後に行うよう直しました。

2023-10-31 01:03 UTC, ota-meshi approved these changes
LGTM!

2023-10-31 01:03 UTC, merged