Draft: VSCodeno
future-architect/vscode-uroborosql-fmt pull request #52
Opened 2024-04-30 06:53 UTC by abcd-ts

Close #19 

## 概要

1. settings.jsonでuroborosql-fmtの設定を指定できるようにしました。
2. settings.jsonで指定したオプションが設定ファイル (`.uroborosqlfmtrc.json`) のオプションが競合した場合は、settings.jsonの値が優先されます (https://github.com/future-architect/uroborosql-fmt/pull/34)

## できていないこと

settings.jsonの内容を設定ファイルに同期するコマンドは未実装です

2024-04-30 07:01 UTC, abcd-ts commented
@ota-meshi 
settings.jsonでオプションを指定するPRを作成しました。
以下2点の確認をお願いしたいです。
1. 不自然なコードがないか
2. settings.jsonの内容を設定ファイルに同期するコマンドをこのPRで実装するか (実装しないようなら、Draft: を外します)

2024-04-30 08:46 UTC, ota-meshi requested changes

2024-04-30 08:46 UTC, ota-meshi commented on server/src/server.ts
> +    Object.entries(restConfiguration).map(([key, value]) => [
`undefined`に置き換えてもkey自体は除外されないので、filter使う方が良さそうです。

```suggestion
    Object.entries(restConfiguration).filter(([, value]) => value !== null)
```

2024-04-30 08:51 UTC, ota-meshi commented
> settings.jsonの内容を設定ファイルに同期するコマンドをこのPRで実装するか (実装しないようなら、Draft: を外します)

コマンドはPRを別にしたほうが、PR一つがシンプルになるので良いことだと思います 😄

2024-04-30 08:56 UTC, ota-meshi commented
> true または false で指定するオプションについて、設定ファイルよりもsettings.jsonの内容を優先する関係上、型を["boolean", "null"] としています。その影響でUI上では settings.jsonで編集 と表示され、チェックボックスで指定することができません。良い案があれば教えていただきたいです。

ここらへん詳しく無いのですが、`type: boolean`にして`default`を削除するのはうまくいかないのでしょうか？
その場合、設定なしの場合に true、 false いがい（つまりnullやundefined）が取得できてほしいということですよね？

2024-04-30 09:06 UTC, ota-meshi commented
> type: booleanにしてdefaultを削除するのはうまくいかないのでしょうか？

試しましたがダメそうですね 😓 
そうすると（変換処理が必要になりますが）以下のような設定にするのはどうでしょうか？

```json
        "uroborosql-fmt.complementAlias": {
          "enum": [
            "on",
            "off",
            "default"
          ],
          "default": "default",
        },
```

2024-04-30 09:14 UTC, ota-meshi commented
>（変換処理が必要になりますが

変換が不要な方法だとこうすることもできることに気がつきました。

```json
          "enum": [
            true,
            false,
            null
          ],
          "default": null,
```

2024-04-30 09:19 UTC, ota-meshi commented on package.json
> +            "number",
ここって`"integer"`って使えませんでしたっけ？あとminimumも指定があるとより良いと思います。

2024-05-02 00:42 UTC, abcd-ts commented on package.json
> +            "number",
ありがとうございます。以下対応しました

1. booleanのオプションについて、enumを使ってUI上で選択できるよう修正しました
2. tabSizeについて、 typeを `integer` に変更し、最小値を0に設定しました

2024-05-02 01:36 UTC, ota-meshi requested changes
変更ありがとうございます！

2024-05-02 01:36 UTC, ota-meshi commented on package.json
> +          "enum": [
ここはnumberなのでenumいらない気がします。

2024-05-02 01:45 UTC, abcd-ts commented on package.json
> +          "enum": [
見落としていました、ありがとうございます。修正しておきました。

また、ここも整数でよさそうなので、numberからintegerに変更しました。

2024-05-02 01:48 UTC, ota-meshi approved these changes
LGTM! Thank you!

2024-05-02 01:49 UTC, merged