Add a command to synchronize the formatter's config file with the workspace settings
future-architect/vscode-uroborosql-fmt pull request #60
Opened 2024-09-02 02:19 UTC by lemonadern

Close #58

2024-09-02 06:02 UTC, tanzaku requested changes

2024-09-02 06:02 UTC, tanzaku commented on package.json
> +        "title": "Synchronize config file with Extension config"
現状では `category` を指定しておらず、uroborosql-fmtのコマンドだとわかりにくいので `Synchronize uroborosql-fmt config file ...` のように拡張名を入れると良さそうです。

eslintでも拡張名を含むタイトルがあるようなので、タイトルに拡張名を入れるのはそんなに不自然ではないのではないかと思っています。
[vscode\-eslint/package\.json at main · microsoft/vscode\-eslint](https://github.com/microsoft/vscode-eslint/blob/700f0b6d1beb88de7706c3237dca683c3aed15b7/package.json#L571)
```json
			{
				"title": "Create ESLint configuration",
				"category": "ESLint",
				"command": "eslint.createConfig"
			},
```

2024-09-02 07:15 UTC, lemonadern commented on client/src/extension.ts
> +          VSCodeConfigPath !== "" ? VSCodeConfigPath : ".uroborosqlfmtrc.json";
monorepoの場合にパッケージを超えて（今回であればclientとserver間で）設定値を共有したいときのプラクティスをあまり知らないのですが、[vscode-eslint](https://github.com/microsoft/vscode-eslint)ではsharedというディレクトリをclient, serverと同じ階層に置き、各パッケージにシンボリックリンクを張ることで設定値の共有を実現しているようです。
- $shared/: https://github.com/microsoft/vscode-eslint/tree/6a6ffb4670bd7ba5ce544c63172aa350c68a7abc/%24shared
- client/src/shared: https://github.com/microsoft/vscode-eslint/blob/6a6ffb4670bd7ba5ce544c63172aa350c68a7abc/client/src/shared
- server/src/shared: https://github.com/microsoft/vscode-eslint/blob/6a6ffb4670bd7ba5ce544c63172aa350c68a7abc/server/src/shared

vscode-eslintに倣った対応方針でよいでしょうか？

2024-09-02 07:37 UTC, tanzaku commented on client/src/extension.ts
> +          VSCodeConfigPath !== "" ? VSCodeConfigPath : ".uroborosqlfmtrc.json";
すみません、異なるパッケージなのを見落としていました。
vscode-uroborosql-fmtはuroborosql-fmtの薄いラッパーで、そこまで頑張って共通化しても恩恵は薄いと思うので、一旦このままでお願いします :bow:

2024-09-03 08:54 UTC, lemonadern commented
#62 に移行

2024-09-03 08:54 UTC, closed without merging